### PR TITLE
Added Support for HmIP-SWO-PL and HmIP-SWO-B

### PR DESCRIPTION
**Pull request by dickesW**
I manually edited the sensors.py on my system to get my "HmIP-SWO-PL" working in Home Assistant. 

It is nearly the same as the "HmIP-SWO-PR": IPWeatherSensor which is already supported with pyhomematic just without the wind direction sensor.  
https://www.eq-3.de/produkte/homematic-ip/homematic-ip-wettersensor-plus.html
The two values for "WIND_DIR" and "WIND_DIR_RANGE" now show "false" as value. Maybe there is a smart way to not create those sensors if they are not available?
Thx

### CODE REVIEW

**Comment by danielperna84** [comment]
You should create a new class (copy the one you are using currently and add _Wind_ to the name), and remove those two unsupported parameters from the `SENSORNODE`-dictionary. Without those the additional sensors should not be created. You then have to add your new class in Home Assistant in the HomeMatic platform everywhere where the old class is also referenced. If that is working for you you can open a pull request so I can merge your changes into pyhomematic.

**Comment by danielperna84** [comment]
Changing the name of the PR would require a change in Home Assistant as well. Could be done, but I don't think it's worth the effort. Your two new classes are very specific, so the _pro_ is just _the other one_ for simplicity. 😆 
I'll merge it the way it is now. As soon as the new pyhomematic version will be released I'll update the component there and add the new classes.

**Comment by dickesW** [comment]
My pull request to add the new classes into home assistant was not accepted:
https://github.com/home-assistant/home-assistant/pull/16172

**Comment by danielperna84** [comment]
I will take care of the PR. Your PR was also missing the reference to the new pyhomematic version. Without that it would have broken relevant thermostats for everybody if this got released.
The other problem is that you removed the whole PR template (with all the checkmarks etc.). You have to leave those in, add a proper description and everything. Not everybody knows about HomeMatic, so without any description only few would be able to handle the PR.

**Comment by dickesW** [comment]
thx @danielperna84 for adding the new classes to homematic. 

is it necessary to add them also here?:
`
HM_IGNORE_DISCOVERY_NODE_EXCEPTIONS = {
    'ACTUAL_TEMPERATURE': ['IPAreaThermostat', 'IPWeatherSensor'],
}
`

I just installed the dev-branch of the homematic component, and its working fine.

**Comment by danielperna84** [comment]
That may actually be the case. Are the sensors missing when the classes are not added to the list?

**Comment by dickesW** [comment]
> Are the sensors missing when the classes are not added to the list?

Yes, Temperature is missing. Adding the classes to the HM_IGNORE_DISCOVERY_NODE_EXCEPTIONS solves it.

**Comment by danielperna84** [comment]
Well in that case it would make sense. Feel free to create the proper PR at the Home Asssistant repository. :)

**Comment by dickesW** [comment]
Done:
https://github.com/home-assistant/home-assistant/pull/17216

**Pull request merged**
