### PR TITLE
Switch type for some HmIP remotes to RemoteBatteryIP

### PR DESCRIPTION
**Pull request by SukramJ**
This pull request does the following: 

Switch type for some HmIP remotes to RemoteBatteryIP
- HmIP-RC8
- HmIP-KRCA
- HmIP-KRC4
... to support LOW_BAT and Voltage.

### CODE REVIEW

**Comment by danielperna84** [comment]
Thanks. Just published a new release a few hours ago, so this will take a while to become effective until I release a new version. 👍

**Comment by SukramJ** [comment]
No problem. Thanks a lot.

**Comment by SukramJ** [comment]
Sorry, i comitted to master.

**Comment by danielperna84** [comment]
No problem in this case.

**Pull request merged**
