### PR TITLE
Adding support for HM-LC-RGBW-WM (Funk-RGBW-Controller)

### PR DESCRIPTION
**Pull request by chr1st1ank**
I implemented support for the HM-LC-RGBW-WM (Funk-RGBW-Controller) which is also mentioned in the [missing devices thread](https://github.com/danielperna84/pyhomematic/issues/28#issue-162335385).

The pull request:
 - adds support for HomeMatic device: HM-LC-RGBW-WM
 - New classes: RGBLight, RGBEffectLight

What is still missing is the integration part to home-assistant. The new device type should be compatible with the home-assistant "light" component. But home-assistant needs to be made aware of the capabilities for color support and color effects.
I know that home-assistant can do this. Can you help me there?

### CODE REVIEW

**Comment by danielperna84** [comment]
Is there any particular reason why you don't use an `__init__` contructor for your classes? For example: I would expect `_color_channel = 2` to be `self._color_channel = 2` in the constructor. And it's similar with the light effects.

**Comment by chr1st1ank** [comment]
Hi @danielperna84,
thanks for taking the time to review my code. 
The reason I chose static attributes instead of assigning instance attributes in the constructor is because they don't ever change. The only advantage of the constructor version I see is to have a constructor parameter e.g. for the list of effect names. Like so:
```python
def __init__(self, effect_list):
    self._effect_list = effect_list
```
But that's also possible if one just overloads the class and add the other constructor style. Either way it is necessary to dig into the homematic specifications to find out the right names and order for the effects.

Therefore I suggest to leave it as is and when we find a second device with these capabilities but different channel or effect list we can make a backward compatible change with an optional parameter like this:
```python
_effect_list = ["default effect list..."]
def __init__(self, effect_list=None):
    if effect_list is not None:
        self._effect_list = effect_list
```

But this is just my two pennies worth. I'm fine with both options and if you prefer a change I'll do it.

**Comment by danielperna84** [comment]
Ok. Another question: You have two classes, but only `RGBEffectLight` is being used. That's the class that Home Assistant needs to know about. Are there also HomeMatic devices which would only use `RGBLight`? If not, then the two classes could be merged into one, because the `RGBLight` wouldn't be reused anyway.

**Comment by chr1st1ank** [comment]
Is suspected there were other Homematic lights with color. But there doesn't seem to be any other device with color. At least I didn't see them in the list of devices for Homematic or Homematic IP.
So I merged the two classes as you suggested. And I also had an error in the collor conversion from RGB colors to the strange HSV color format used for Homematic. White wouldn't have worked.

Now the following test runs through perfectly:
```python
import os
from time import sleep
from pyhomematic import HMConnection

deviceid = "NEQ0184008"

# Create server thread
pyhomematic = HMConnection(remote="192.168.4.5", remoteport=2001,
                           systemcallback=lambda *args: None)
pyhomematic.start()
sleep(2)

# Light tests
print("Light on")
pyhomematic.devices['default'][f'{deviceid}'].on()
pyhomematic.devices['default'][f'{deviceid}'].set_color(255, 255, 255)
sleep(3)

print("Light off")
pyhomematic.devices['default'][f'{deviceid}'].off()
sleep(3)

print("Light 50%")
pyhomematic.devices['default'][f'{deviceid}'].set_level(0.5)
sleep(3)
assert 0.5 == pyhomematic.devices['default'][f'{deviceid}'].get_level()

print("Red")
pyhomematic.devices['default'][f'{deviceid}'].set_color(255, 0, 0)
sleep(3)

print("Green")
pyhomematic.devices['default'][f'{deviceid}'].set_color(0, 255, 0)
sleep(3)

print("Blue")
pyhomematic.devices['default'][f'{deviceid}'].set_color(0, 0, 255)
sleep(3)

print("Yellow")
pyhomematic.devices['default'][f'{deviceid}'].set_color(255, 255, 0)
sleep(3)

print("white")
pyhomematic.devices['default'][f'{deviceid}'].set_color(255, 255, 255)
sleep(3)

print("Slow change")
pyhomematic.devices['default'][f'{deviceid}'].set_effect('Slow color change')
sleep(3)
assert 'Slow color change' == pyhomematic.devices['default'][f'{deviceid}'].get_effect()

print("Waterfall")
pyhomematic.devices['default'][f'{deviceid}'].set_effect('Waterfall')
sleep(3)
assert 'Waterfall' == pyhomematic.devices['default'][f'{deviceid}'].get_effect()

# Disconnect from HM
pyhomematic.stop()
```
Most colorful software test I ever run. Luckily my family is asleep ;-)

**Comment by chr1st1ank** [comment]
I also tried to incorporate this into home-assistant in a docker environment. But for now I only partially succeeded.
I added the new class to the list the file `homeassistant/components/homematic/__init__.py` which defines the light devices:
```python
DISCOVER_LIGHTS: ['Dimmer', 'KeyDimmer', 'IPKeyDimmer', 'RGBEffectLight']
```
This assigns the new pyhomematic actor class to the HMLight class in homeassistant/components/light/homematic.py. And this works. I can dim the light then.

But for the colors it needs a little more. One of my attempts was to change the HMLight class and add this:
```python


    @property
    def supported_features(self):
        """Flag supported features."""
        if "Colorful device": # <-- still pseudocode here!
            return SUPPORT_BRIGHTNESS | SUPPORT_EFFECT | SUPPORT_COLOR
        return SUPPORT_HOMEMATIC

    @property
    def color(self):
        return self._hmdevice.get_color()

    @color.setter
    def color(self, rgb_color):
        return self._hmdevice.set_color(*rgb_color)

    @property
    def effect_list(self) -> list:
        return self._hmdevice.get_effect_list()

    @property
    def effect(self) -> str:
        return self._hmdevice.get_effect()

    @effect.setter
    def effect(self, effect_name: str):
        return self._hmdevice.set_effect(effect_name)
```
I think this would work. But I didn't find a solution yet to tell the "colorful" devices from the normal dimmers. There is just some pseudocode in this line. 
I also tried to add a separate class but didn't find the right way to find out which kind of device I have in the loop which creates the HMLight objects. That's this part here in the same file:
```python

def setup_platform(hass, config, add_entities, discovery_info=None):
    """Set up the Homematic light platform."""
    if discovery_info is None:
        return

    devices = []
    for conf in discovery_info[ATTR_DISCOVER_DEVICES]:
        new_device = HMLight(conf) # <-- Maybe insert an if-statement based on the device type?
        devices.append(new_device)

    add_entities(devices)
```

It would be so nice to see the color LEDs in the home-assistant frontend. It is one of the last things I still didn't manage to connect.

**Comment by danielperna84** [comment]
I think you should be able to get the class with [`class_name = device.__class__.__name__`](https://github.com/home-assistant/home-assistant/blob/782a90a535713f29afb0943a55394b1709486294/homeassistant/components/homematic/__init__.py#L485) within the light platform. So ideally there would be some kind of mapping at the top of the file where it's easy to lookup if the class supports color (or other effects). Like `SUPPORT_MAPPING = {"SUPPORT_COLOR": ["ClassnameInPyhomematic",...]}

**Comment by chr1st1ank** [comment]
Ok, i will try it. Maybe you wait with merging until it works.
I just saw that Homeassistant moved to HS color model earlier this year and I now took RGB colors. They would just be converted back and forth. That's maybe not the best style.

Give me a couple of days, I will write again.

**Comment by danielperna84** [comment]
We only query for states on startup. So yes, after that, we only listen to the events the CCU sends out and use those to update the state in Home Assistant. So probably you have to include the `COLOR` and `PROGRAM` parameters in a similar fashion as other devices like sensors have the SENSORNODE stuff in their `__init__`. The problem with that would be though, that using these nodes would result in extra entities. I'm not sure how that should be addressed. My first thought would be to register a callback within your new class that updates internal class variables for the color and program, which you then could use later on.

**Comment by chr1st1ank** [comment]
I like the callback idea and would add a callback function and some internal variables to track the state in my `ColorEffectLight` class. But I have been trying to implement it for hours now.

A `self.setEventCallback()` does nothing when I call it in the `__init__` function of my class. I varied the parameters to `setEventCallback` to get into all the branches of its if statements:
https://github.com/danielperna84/pyhomematic/blob/5b6dcbcfe069aec7ba257584d3988460e0c2dcd2/pyhomematic/devicetypes/generic.py#L353-L367

I don't achieve anything because when the `__init__` function is executed the list of channels in `self._hmchannels` is empty. It is only filled at some mysterious later point.

When I use the setEventCallback from outside like this it does its job:
```python
deviceid = "NEQ0184008"
from pyhomematic import HMConnection
from pyhomematic.devicetypes import actors

def syscb(src, *args):
    return

pyhomematic = HMConnection(remote="192.168.4.5", remoteport=2001, systemcallback=syscb) # Create server thread
pyhomematic.start() # Start server thread, connect to homegear, initialize to receive events

def eventcallback(address, interface_id, key, value):
    print("CALLBACK: %s, %s, %s, %s" % (address, interface_id, key, value))

pyhomematic.devices['default'][f'{deviceid}'].setEventCallback(eventcallback)
```
It is getting frustrating. I know that it will be no more than maybe 50 lines of code when I have it. Yet it is so hard for me to work out how the classes work together.

Any idea how I can set a callback inside my class _after_ the list of channels has been populated?

**Comment by danielperna84** [comment]
Doesn't someting like the following work in the init?

```python
...
    __init__...
        def mycallback(src, *args):
            return
        self._eventcallbacks.append(mycallback)
```
Maybe you can use [partial](https://docs.python.org/2/library/functools.html#functools.partial) to pass further data (like the object itself) to the callback. We also do that in the HASS component [here](https://github.com/home-assistant/home-assistant/blob/14ad5c00066e717d44a74e759e9c7f53147fc1a6/homeassistant/components/homematic/__init__.py#L283).

**Comment by chr1st1ank** [comment]
Hm, no sadly this doesn't work. I tried it. But it does the same as setEventCallback(mycallback, channel=0). The callback is never called.
This is because the callback is only for the device itself ("NEQ0184008" for me). But the events are only triggered for the channels (e.g. "NEQ0184008:2"), which I can see from the output of the logging module.
I need to set a callback to the channels. But for this I need to know when they become available. It seems to be after the `__init__` of HMDevice is through already.

**Comment by danielperna84** [comment]
I think I have an idea of a general solution that might be useful for other purposes as well.

[Here](https://github.com/danielperna84/pyhomematic/blob/5b6dcbcfe069aec7ba257584d3988460e0c2dcd2/pyhomematic/_hm.py#L189) we always call the [event](https://github.com/danielperna84/pyhomematic/blob/5b6dcbcfe069aec7ba257584d3988460e0c2dcd2/pyhomematic/devicetypes/generic.py#L53) method of relevant device-objects. Currently we only set the `UNREACH` state there and call the sub-callbacks that have been added for the channel.

My idea now would be to have something like `self.VALUES = {}`, which then would be populated as events arrive. Over time it would look like `{"STATE": False}` and so on. So the last pushed state could be queried like `self.VALUES.get("STATE")`, and everything that `is not None` is a real value we have received from the CCU.
This would apply to the channel-objects, so this should somehow also be pushed to the top-level object. There then something like `self.VALUES.get(channel, {}).get("STATE")` could be done.

I haven't thought through it completly yet, but that would allow you to either use the _cached_ state, and if that's `None` use the `getValue` once to cache it manually, and then subsequent updates will use the cached value.

What do you think about that?

**Comment by chr1st1ank** [comment]
Yes, this sounds like a good idea. In this case the HMGeneric class could also provide a function like updateValue(valuename) which queries and caches a value on demand if it is still 'None'.

But I would like to understand how this is done for all the other devices. For example the "KeyBlind" actor tracks the state of the shutters and the HMThermostat tracks for example the room temperature. 
They seem to write the value names they are interested in into some of the dictionaries like "SENSORNODE" or  "WRITENODE". To query the values they use calls to for example `getWriteData` of HMDevice [for example here](https://github.com/danielperna84/pyhomematic/blob/5b6dcbcfe069aec7ba257584d3988460e0c2dcd2/pyhomematic/devicetypes/thermostats.py#L34). If I am correct, the call stack is like this:
```
HMDevice.getWriteData -> HMDevice._getNodeData -> HMChannel.getValue
```
The last function then directly queries the CCU which is the "_proxy" object. Is this right? And are then all the get() methods synchronously queried from the CCU at the moment?

**Comment by danielperna84** [comment]
> But I would like to understand how this is done for all the other devices.

Currently the device objects don't know anything about their state. That was never needed because Home Assistant uses those node-dictionaries to create the HASS-entities, and also over there callbacks are added which update the state of the entity by looking at the events that arrive. So these classes in pyhomematic actually just kind of summarize what the device is capable of doing, but keeping track of the state is done in the Home Assistant code.

This has the advantage, that more complex devices can be made ob up several paramters. Like for thermostats, where in Home Assistant we just have one entity, but it consists of several different parameters that all work together.

But this also brings some limitations. ioBroker for example does it differently. There you just get an element for every parameter the device has. There's no real concept of a complex device. So as a user you have to see for yourself how you automate by using those values and how to visualize them. But it provides much more flexibility. It's kind of more _low level_.

So my proposal from above would be roughly like having all those paramters that ioBroker has as dict-items in the device-object while retaining the current architecture where multiple parameters can make up a single device.

I'll try to have a look at this paramter-thing I thought about tomorrow. I'll keep you updated. Meanwhile I have merged another PR, which unfortunately now results in a conflict for your PR. So you already can update your code to resolve the conflicts. I'm pretty sure my changes will only be in the `generic.py` file, maybe `_hm.py` too. But I won't be touching `actors.py`. So you can prepare your code safely.

**Comment by danielperna84** [comment]
Your code is pretty much what I had in mind. So you can include this in your PR as well. 🙂

**Comment by danielperna84** [comment]
And I actually don't think timestamps and garbage collection do anything good in this case. Device only have a couple of parameters. Along with their values that won't be more than 100 bytes (just a wild guess). I believe the CPU cycles that it would take to clean everything up as every event comes by have a greater impact on performance than the memory we could save. So I would leave it as it is.

**Comment by chr1st1ank** [comment]
Yes, you were right with regards to memory. I did some quick memory profiling, just to make sure. But the whole memory consumption stays at stable 38MB for a running pyhomematic client in our house, no matter what I do with all the connected devices.

The value caching is implemented. I also replaced the "_unreach" attribute which is redundant now. Instead the PARAM_UNREACH value is also stored in the _VALUES dict.
 
For the color light I used the  "WRITENODE" mechanism on top which is used by the normal Dimmer device. Otherwise the states don't seem to get updated on every change. But I still needed the new value cache to because the getWriteData() makes home-assistant generate warnings as well, because it does I/O.
Now the LED controller now seems to work perfectly in home-assistant. I updated my [gist](https://gist.github.com/chr1st1ank/742997ea102f734d2a13db323fac3f15) which shows what I did in home-assistant.

Maybe we can refactor the one or other get_something() call in the future to use the cache. But I don't want to mess up even more of your pretty little repository ;-)

**Comment by danielperna84** [comment]
Looking good. One thing: You have set the default for _unreach_ to `False`. What happens when you startup Home Assistant and a device is unreachable? And does it correctly become available when plugging it back in?

**Comment by chr1st1ank** [comment]
Oh yes, good spot. I changed added another line to the init function, so that the default is None again.
Apart from where the information is stored, the unreach stuff has not changed. All uses were encapsulated behind the UNREACH property.

I also commited my .gitignore by mistake and reverted that as well now.

**Comment by danielperna84** [comment]
Ok, so this is ready to merge then, correct?

**Comment by chr1st1ank** [comment]
Yes, it is.

**Comment by danielperna84** [comment]
The PR for Home Assistant is here: https://github.com/home-assistant/home-assistant/pull/18499
Could you have a look at the comment regarding the `has_attr`?

**Pull request merged**
