### PR TITLE
Add IP Cover classes and helper class for tiltable covers

### PR DESCRIPTION
**Pull request by steffenslavetinsky**
This solves the Problem described in #107 and adds tiltable covers to the HmIP-BBL.
The Helper should also work for other tiltable blinds but I can't test it.

I also implemented an extension to the home assistant homematic covers. What would be the best way to send a pull request to home assistant? Should i just reference this pull request or should i wait until it is reviewed and merged?
I am using this code in my home for a week now and as far as I can tell the fix with setting the level afterwards works.

### CODE REVIEW

**Comment by danielperna84** [comment]
Looking good. Can you post here which changes you have added to the HA cover platform?
I'll make a new pyhomematic version shortly. Once that's done I'll get the required changes not related to this PR into HA. Once the new pyhomematic version is referenced there, you can create your own separate PR with only the needed changes. Or you report what needs to be done and I'll included it in my PR. Whatever you like more.

**Comment by steffenslavetinsky** [comment]
Basically all i changed was to add the required methods to HMCover.
The decision weather it is titlable or not takes place in the `_init_data_struct` method.

```python
    def _init_data_struct(self):
        """Generate a data dictoinary (self._data) from metadata."""
        self._state = "LEVEL"
        self._data.update({self._state: STATE_UNKNOWN})
        try:
            self._data.update({'LEVEL_2': self._hmdevice.get_cover_tilt_position()})
        except:
            pass
```

Home Assistant decides whether a cover is tiltable or not by getting the property `current_cover_tilt_position` and there i test if LEVEL_2 is in self._data. When it is not, None is returned and Home Assistant assumes that the cover is not tiltable. Otherwise the tilt value is returned and Home Assistant shows the appropriate controls and uses HMCover's cover_tilt methods.

**Comment by danielperna84** [comment]
I have published pyhomematic 0.1.37 and have created the PR for HA that references the new version: https://github.com/home-assistant/home-assistant/pull/11578
I have added the new classes [here](https://github.com/danielperna84/home-assistant/blob/616d447ffac78ec2329a0938f76f2e9c63b67860/homeassistant/components/homematic/__init__.py#L81), but haven't done the other changes. You can do that with your own PR as soon my changes have been merged.

**Comment by steffenslavetinsky** [comment]
Yes, I will create the PR tomorrow. Didn't expect them to merge that quick!

**Pull request merged**
