### PR TITLE
Add basic support for HmIP-SPDR (Passage Sensor)

### PR DESCRIPTION
**Pull request by noxhirsch**
Add basic support for HmIP-SPDR passage sensor with direction recognition.
You get a PRESS_SHORT on channel 2 for right to left and on channel 3 for left to right.

### CODE REVIEW

**Comment by danielperna84** [comment]
Is this device capable of doing other things that might be of interest? A quick glimpse at the product description says that it alos counts people. I assume that would be useful as a sensor entity.

**Comment by noxhirsch** [comment]
Yes, the sensor can count how many people are going through, but there are two reasons why I didn't implement that:

1. I don't know how 😄 
2. The main problem is, that you can't do anything to the numbers. I want to use it to count how many people are going into a room and how many left it. So I can turn on some stuff when people are in the room and turn it of when everybody is out (faster and more reliable as with a normal pir sensor)
But I want to be able to reset that value if the sensor miscounts, which is not possible with the value from Homematic.

Here's the (cleaned up) output from pyhomematic.devicetypes.generic (HMGeneric.event) which comes with every sensor update:
`address=XXXXX:0, interface_id=homeassistant-ip, key=CONFIG_PENDING, value=False
address=XXXXX:0, interface_id=homeassistant-ip, key=RSSI_DEVICE, value=-47
address=XXXXX:0, interface_id=homeassistant-ip, key=LOW_BAT, value=False
address=XXXXX:0, interface_id=homeassistant-ip, key=UNREACH, value=False
address=XXXXX:2, interface_id=homeassistant-ip, key=PRESS_SHORT, value=True
address=XXXXX:0, interface_id=homeassistant-ip, key=DUTY_CYCLE, value=False
address=XXXXX:0, interface_id=homeassistant-ip, key=LOW_BAT, value=False
address=XXXXX:0, interface_id=homeassistant-ip, key=UNREACH, value=False
address=XXXXX:0, interface_id=homeassistant-ip, key=RSSI_DEVICE, value=-50
address=XXXXX:0, interface_id=homeassistant-ip, key=OPERATING_VOLTAGE_STATUS, value=0
address=XXXXX:0, interface_id=homeassistant-ip, key=OPERATING_VOLTAGE, value=3.0
address=XXXXX:2, interface_id=homeassistant-ip, key=PASSAGE_COUNTER_VALUE, value=45
address=XXXXX:2, interface_id=homeassistant-ip, key=PASSAGE_COUNTER_OVERFLOW, value=False
address=XXXXX:2, interface_id=homeassistant-ip, key=LAST_PASSAGE_DIRECTION, value=False
address=XXXXX:2, interface_id=homeassistant-ip, key=CURRENT_PASSAGE_DIRECTION, value=True
address=XXXXX:3, interface_id=homeassistant-ip, key=PASSAGE_COUNTER_VALUE, value=53
address=XXXXX:3, interface_id=homeassistant-ip, key=PASSAGE_COUNTER_OVERFLOW, value=False
address=XXXXX:3, interface_id=homeassistant-ip, key=LAST_PASSAGE_DIRECTION, value=True
address=XXXXX:3, interface_id=homeassistant-ip, key=CURRENT_PASSAGE_DIRECTION, value=False`

Interestingly there's no output from channel 4 which you can set to "count both directions" (these values are also integrated in the output of channel 2 & 3), "count direction X" or "difference in direction X" or inactive.

**Comment by noxhirsch** [comment]
homematic_spdr

**Comment by danielperna84** [comment]
Could you also post a screenshot of how the states of the sensor look in the UI? In the end it would be the goal to replicate what we can see on the CCU. And does the value for the counted people always increase? Right now it looks like 45 people have passed in the one direction. But I assume this is just a counter that never goes down.

**Comment by noxhirsch** [comment]
The sensor does not exist in the UI at the moment - it's just like the HmIP wall switches, which only appear as keypress events when someone pressed a button.
Sadly I don't really understand how your great piece of software works and everything I modified was more like a lucky guess 😉 Maybe you can help where I have to change things here?
As far as I understand, the values for the counted people increase until the upper limit of 1000 is reached (I assume that it'll reset to 0). Also the number seems to get a reset sometimes, because it's smaller than before. Maybe on restart of the CCU2 or every day (I try to check that ASAP).
But normally it just increments the value of the corresponding channel.

**Comment by danielperna84** [comment]
I mean how it looks in the UI of the CCU. People tend to want to see in the HASS UI what they see on the CCU. So it would help me to see how it _should_ look.

**Comment by noxhirsch** [comment]
My bad! Here's the screenshot:
homematic_spdr2

By the way: The value gets a reset when it exceeds 127 (and when you trigger the sabotage sensor according to some forum post).

**Comment by danielperna84** [comment]
Please do the following in `sensors.py`:
Add `HelperEventRemote` to the import at the top so it looks like this:
```python
from pyhomematic.devicetypes.helper import (HelperLowBat, HelperSabotage,
                                            HelperLowBatIP, HelperSabotageIP,
                                            HelperBinaryState,
                                            HelperSensorState,
This --->                                   HelperWired, HelperEventRemote)
```
Then add this class to the file:
```python
class IPPassageSensor(HMSensor, HMBinarySensor, HelperEventRemote, HelperLowBatIP):
    """HomeMatic IP Passage Sensor. #2 = right to left, #3 = left to right"""

    def __init__(self, device_description, proxy, resolveparamsets=False):
        super().__init__(device_description, proxy, resolveparamsets)

        # init metadata
        self.SENSORNODE.update({"PASSAGE_COUNTER_VALUE": self.ELEMENT})
        self.BINARYNODE.update({"PASSAGE_COUNTER_OVERFLOW": self.ELEMENT,
                                "LAST_PASSAGE_DIRECTION": self.ELEMENT,
                                "CURRENT_PASSAGE_DIRECTION": self.ELEMENT})
        self.ATTRIBUTENODE.update({"RSSI_DEVICE": [0]})

    @property
    def ELEMENT(self):
        return [2, 3]
```

Finally add the new class to the `DEVICETYPES` dictionary all the way at the bottom so it looks like this:
```python
DEVICETYPES = {
    "HM-Sec-SC": ShutterContact,
    "HM-Sec-SC-2": ShutterContact,
    "HM-Sec-SCo": ShutterContact,
...
...
    "HmIP-SPDR": IPPassageSensor,
```

Then you need to let Home Assistant know about this new class. This is done in the file [homeassistant/components/homematic/\_\_init\_\_.py](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homematic/__init__.py). Since we have two types of sensors (binary and numeric) you have to add the new class (`IPPassageSensor`) to 2 places: [here](https://github.com/home-assistant/home-assistant/blob/02238b6412ce271010b4227f45344173b9f525ea/homeassistant/components/homematic/__init__.py#L74) and [here](https://github.com/home-assistant/home-assistant/blob/02238b6412ce271010b4227f45344173b9f525ea/homeassistant/components/homematic/__init__.py#L83).

Once you have done that and restart Home Assistant you should get the events just like before, plus 8 entities you can work with. 1 sensor and 3 binary sensors per channel 2 and 3. In the long run this should get refinded to just have one entity for the current and the last direction. But for a first implementation this will be ok. Now I just need to know if the code I have provided here does its job correctly.

**Comment by noxhirsch** [comment]
You're great! This works perfectly 👍 
spdr_binary
spdr_sensor

**Comment by danielperna84** [comment]
Great. One more question: Are the parameters `LAST_PASSAGE_DIRECTION` and `CURRENT_PASSAGE_DIRECTION` from both channels always inverted? To me it would seem logical, that if for example `CURRENT_PASSAGE_DIRECTION` on channel 2 is on, then it has to be off on channel 3. So we would actually only need one channel for these two parameters, and map their true/false values to "left to right" and "right to left".

**Comment by noxhirsch** [comment]
No, it's not always inverted. Only when someone enters and then leave the room. If two (or more) people pass the sensor in the same direction, then CURRENT_PASSAGE_DIRECTION and LAST_PASSAGE_DIRECTION are both true for one channel and both false for the other channel.

**Comment by danielperna84** [comment]
To clarify: what I mean is that if `CURRENT_PASSAGE_DIRECTION` is `True` on channel 2, it has to be `False` on channel 3. If the both are `True`, you'd have to walk in both directions at the same time. And the same for `LAST_PASSAGE_DIRECTION`. So the inversion I assume is across both channels. My logic is, that we only need those two paramters from one channel, because the other channel always has the flipped values.

**Comment by noxhirsch** [comment]
Oh sorry - of course, you're right! 👍

**Comment by danielperna84** [comment]
Then please replace the class from above with this code:

```python
class IPPassageSensor(HMSensor, HMBinarySensor, HelperEventRemote, HelperLowBatIP):
    """HomeMatic IP Passage Sensor. #2 = right to left, #3 = left to right"""

    def __init__(self, device_description, proxy, resolveparamsets=False):
        super().__init__(device_description, proxy, resolveparamsets)

        # init metadata
        self.SENSORNODE.update({"PASSAGE_COUNTER_VALUE": self.ELEMENT})
        self.BINARYNODE.update({"PASSAGE_COUNTER_OVERFLOW": self.ELEMENT,
                                "LAST_PASSAGE_DIRECTION": [2],
                                "CURRENT_PASSAGE_DIRECTION": [2]})
        self.ATTRIBUTENODE.update({"RSSI_DEVICE": [0]})

    @property
    def ELEMENT(self):
        return [2, 3]
```

With that you should only get one `LAST_PASSAGE_DIRECTION` and `CURRENT_PASSAGE_DIRECTION` sensor. Besides those only showing binary states this would still be all that's needed from a technical perspective, correct?

**Comment by noxhirsch** [comment]
I've just replaced it and everything is working fine. And from a technical perspective it's all you need. I assume that you want to replace the binary sensor to something more self-explanatory like LAST_PASSAGE_DIRECTION: left-to-right / ltr?
By the way: I think it would be usefull to replace the channel numbers in the sensor names with e.g. rtl & ltr. 
binary_sensor.spdr_3_passage_counter_overflow => binary_sensor.spdr_ltr_passage_counter_overflow

**Comment by danielperna84** [comment]
The names of the entities are generated automatically. So we can't change that unfortunately.
How the values of true/false will be displayed depends on the code in Home Assistant. I'll have a deeper look at that some other time. For now I just wanted to be sure it's working from the pyhomematic side.
If you're fine with that I would close this PR and push the code I have come up with.

**Comment by noxhirsch** [comment]
Okay, I think the numbers in the channel names is not a big deal. 
And binary_sensor is also good as it is.
I'm fine with this, so you can close it. Thank you very much! 👍

**Comment by danielperna84** [comment]
Here's my code for HASS: https://github.com/danielperna84/home-assistant/blob/homematic_hmip_spdr/homeassistant/components/homematic/__init__.py
Could you please verify that you get everything as discussed? If yes, then I'll open the PR to get this into HASS.

**Comment by noxhirsch** [comment]
I've just checked and everything we've discussed is working fine 👍

**Comment by danielperna84** [comment]
PR at HASS has been merged. So it will work with the next release. 👍

**Comment by noxhirsch** [comment]
Yippie! Thank you! 👍

**Pull request closed without merging**
