### PR TITLE
HmIP-BWTH add switching state for heating valve

### PR DESCRIPTION
**Pull request by sVnsation**
Added the switching state for the heating valve on channel 8.
for devices: HmIP-BWTH and HmIP-BWTH24

I'm not sure if it would be better to implement a class HelperValveBinaryState?
But currently i don't know how to rename/map the "STATE" channel.

image

### CODE REVIEW

**Comment by danielperna84** [comment]
I think it's ok having this as an attribute. Not everyone will want the additional binary_sensor entity.

**Comment by emufan** [comment]
@sVnsation Is this already in HA? Perhaps I miss the trees in the wood, but I'm not able to find the attribute.

**Comment by sVnsation** [comment]
The [const.py](https://github.com/home-assistant/core/tree/dev/homeassistant/components/homematic) in HA needs a modification. Add the STATE i.e like this:

```
HM_ATTRIBUTE_SUPPORT = {
    "LOWBAT": ["battery", {0: "High", 1: "Low"}],
...
    "STATE_UNCERTAIN": ["state_uncertain", {}],
    "STATE": ["attribute_state", {}],
}
```

**Comment by danielperna84** [comment]
@sVnsation 

I recommend you create a PR at the Home Assistant Repo for that. 👍

**Comment by emufan** [comment]
@sVnsation I second this, but I would recommend to have a _better name" than attribute_state. e.g. switch_state or whatever is more pointing to what it is.

BTW: Tested and it is working.

**Comment by sVnsation** [comment]
In theory this attribute "STATE" can be anything for other devices... not only a switch. So i picked a generic name. 
I'm not entirely happy with this, thats also the reason why i didn't created a PR, yet.

**Comment by emufan** [comment]
@sVnsation Yes. But attribute_state is too generic. But I would like to have a PR as well. Why having this in pyhomematic and then in HA only "for us" with a modification. Shouldn't be that hard to have a good name. heat_switch_state or heating_valve_state or ...

**Comment by sVnsation** [comment]
@danielperna84 Is there a way to rename the attribute STATE to VALVE_SWITCH_STATE for class IPThermostatWall230V only?

**Comment by danielperna84** [comment]
I actually think it should just be `state`. That's exactly the name in the devices paramset. If somebody ever investigates, a renamed attribute would be confusing. All the other entities also always use the exact parameter name in their entities. Hence I vote for consistency. And that way also other devices could have a state-attribute the same way.

**Comment by emufan** [comment]
@danielperna84  Hm, but what if you have ```state``` on different channels of the same device? E.g. this one. afaik there is ```state``` on 8 and 10. But of course, as long as only one state is implemented and in total there is only this one in BWTH on channel 8, is is working. And here the both, 8 and 10 states should have the same state anyway.

Are there other cases with same attribute on different channels and how did you deal with them in the past?

Anyway and BTW: It is working great in HA

image

**Comment by sVnsation** [comment]
There are cases: for example the BROLL. SENSORNODE (channel=3) and WRITENODE (channel=4) both set the LEVEL value.
The NODE that reports last wins. As you can see it isn't dealt with it in the past. 


[actors.py](https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/actors.py)
```
class IPBlind(GenericBlind, HelperRssiPeer):
...
        self.SENSORNODE.update({"LEVEL": [3]})
        self.WRITENODE.update({"LEVEL": self.ELEMENT})
```

**Pull request merged**
