### PR TITLE
Modified constructor - added additional devices

### PR DESCRIPTION
**Pull request by jazzaj**
Constructor: One of my devices did not have a FAMILIY parameter which caused trrouble. Using "get" seems to work.
Add. Devices: Added dimmer and switch. Created stub for remote and CCU

### CODE REVIEW

**Comment by danielperna84** [comment]
Great improvement through using the .get()!

1. Line 414 still says RollerShutter.
2. Line 463 - 467 have commented code. If that's of no use, that should be removed.
3. I would suggest to add objects to DEVICETYPES if they really exists. CCU and remote don't in the current code.

**Comment by danielperna84** [comment]
Accidentally closed. Please re-open pull request.

**Comment by jazzaj** [comment]
Thanks for your helpful feedback. Tried to include it all. Not sure if my edits ended at the right place (Commit 2)

**Comment by danielperna84** [comment]
1. Line 87 seems to have trailing whitespace. Python is picky about whitespace, so am I. :D
2. The way I am logging is "Classname.method/property/whatever". You correctly changed the classname from HMRollerShutter to HMDimmer. But you kept the "seek", which in line 414 should be "level", and in line 468 should be "state".
3. The state-getter returns "on" or "off", which is disjunct with how you set it. If it returns "on" and "off", you have to set it using "on" and "off". But instead I would actually just use 0 and 1 instead of strings. And to make it more stable I'd do ```onoff = bool(onoff)``` (0 = off, > 0 = on). The getter then would just return 0 or 1. Which wouldalso  make it easier to query the state when using the module programmatically.


.

**Comment by danielperna84** [comment]
Looking good now. I'll do the pull. :)

**Pull request merged**
