### PR TITLE
Added Devices BC-SC-Rd-WM and BC-PB-2-WM

### PR DESCRIPTION
**Pull request by tringler**

### CODE REVIEW

**Comment by tringler** [comment]
FYI - In Homeassistant I get:

```
17-01-16 21:04:30 ERROR (Thread-9) [pyhomematic.devicetypes.generic] HMGeneric.getValue: LOWBAT on JMD4015744:1 Exception: <Fault -5: 'Unknown parameter.'>
17-01-16 21:04:30 ERROR (Thread-9) [pyhomematic.devicetypes.generic] HMGeneric.getValue: ERROR on JMD4015744:1 Exception: <Fault -5: 'Unknown parameter.'>
```

But on the homeassistant sensor the battery state is `high`. It is expected? Maybe a false positive error?

**Comment by danielperna84** [comment]
My guess would be, that MAX shutter contacts use different parameters / channels for error and lowbat. This in turn would require you to create an extra class similar to `IPShutterContact`, but with helpers modified to respect the internals of the MAX device. The MAX thermostats do this differently as well compared to HomeMatic thermostats. So in this case it would be your task to find out what channels and parameters are used, or if they even have those.

**Comment by tringler** [comment]
@danielperna84 I will take a look on it the next days and add some commits if possible.

**Comment by jannau** [comment]
I didn't noticed I get the same errors with 'BC-SC-Rd-WM-2'. The MAX devcies have no Error/Sabotage attribute and the LOWBAT attribute is on channel 0. I'll fix it in a moment.

**Comment by tringler** [comment]
Thanks for the hint! It's working in my HASS instance now. I'm getting battery states and RSSI values. It's fixed with https://github.com/danielperna84/pyhomematic/pull/53/commits/e62653396098482435cf1f647461f31cf6417fc6

**Comment by danielperna84** [comment]
There's still a conflict caused by the other ShutterContact that has to be a MaxShutterContact. My PR in your fork fixed that, and if you merge it this PR should be able to merge.

**Comment by tringler** [comment]
Sorry, I'm still a beginner in GitHub. I hope you can work with it now?

**Comment by danielperna84** [comment]
Hhmm, something went wrong with that. I think my PR was wrong. Let me check how to resolve this.

**Comment by tringler** [comment]
We are talking about two codelines :) - Before you invest some time to solve that just reject the PR and I will push a new PR.

**Comment by danielperna84** [comment]
It's already fixed and merged. ;-)

**Pull request merged**
