### PR TITLE
"working" flag + device names

### PR DESCRIPTION
**Pull request by jazzaj**
Working flag is True while devices are created.
Devices name will be downloaded from CCU if the XML-API is installed

### CODE REVIEW

**Comment by danielperna84** [comment]
For the working flag: This does not work for me. Within the RPCFunctions-object it is working as designed. But the purpose of this flag is to test it by doing something like ```if homematic._server.working:```, which always is set to False in my tests.
It seems like the value is bound to its scope within the object, even though ```global``` is being used. Not sure why that happens.

I can't test the device names functionality. I assume it is working for you. If you devide the code of this pullrequest into two, I would pull the one with the XML-API and have a look at the working-topic.

**Comment by danielperna84** [comment]
Correction: The flag does change. But only for a brief moment while the deviceobjects are actually created, not during the time we are waiting for them. So the implementation does not provide any benefits. And thinking of it, waiting for the devices is not "working". We're essentially just waiting for a new_devices-event, which can occur anytime, and is handled already.
Since this is needed for HA I suggest to let the HA-component attatch a callback which waits for the new_devices-event, and creates the HA platforms as soon as the event gets triggered.
I'll habe a look at your HA-related code and see what I can work out.

**Comment by jazzaj** [comment]
This is how I apply the `working` flag:

`pyhomematic.create_server(...)
pyhomematic.start()
while not pyhomematic.devices or pyhomematic._server.working:
    pass`

This behavior might not be obvious but from my understanding it matches good to the term 'working' (while the app is waiting for the first call of addDevices this would be not be 'working' but 'waiting' for me).
Other interpretations and implementations are possible but than I would vote for a renaiming the flag (e.g. 'initializing') or introducing a function instead (e.g. waitForDevices()). The advantage I see in the current implementation is that it is possible to react to the situation that no decives are created...

Please note: The createDeviceObjects call in __init__ does never create any devices for me, as _devices_raw is always empty at this point of time...

**Comment by danielperna84** [comment]
Because of the switch from homematic to pyhomematic this can't be merged. I've copied the code manually, fixed a bug, und pushed it into the repository. Closing the PR.

**Pull request closed without merging**
