### PR TITLE
HmIP-MIOB

### PR DESCRIPTION
**Pull request by danielperna84**
Implement HmIP-MIOB.

In Home Assistant add `IPMultiIO` to `DISCOVER_SWITCHES`, `DISCOVER_SENSORS` and `DISCOVER_BINARY_SENSORS`.

### CODE REVIEW

**Comment by mobelix79** [comment]
Hi. Thanks for the real fast answer and implementation. For sure I will support as much as I can. Maybe I need some help as I'm a real newbie in Home Assistant. Here the screenshots of the device setting taken out of my Homematic WebUI piVCCU 3.41.11-12. For me personally the "Analoger Ausgang" is the one I am interested to have in Home Assistant. 
image
screenshot_2
screenshot_3
image
image
image

**Comment by danielperna84** [comment]
Looking at the screenshots the channels that I have used for the switches might be incorrect. Your screenshots show 3 and 7, the specification looks more like 2 and 6. So this is something you will have to test.

What kind of Home Assistant installation do you have? The easiest way of testing without impairing your running system would be to set up a virtual machine and follow [these](https://www.home-assistant.io/docs/installation/virtualenv/) installation instructions. After that configure Home Assistant so that HomeMatic IP devices are working (if you also have other types, don't configure them because the will just distract from the data that is relevant for us). Once that is done, you have to make two changes in the source code:

1. From within your _venv_ (mentioned in the linked instructions) navigate to the folder `lib/python3.5/site-packages/pyhomematic/devicetypes`. Depending on the system in can also be `python3.6`. Anyways, within that folder you'll find the `actors.py` file. Edit that file and manually add the changes that you see in the pull request related to that file.
2. From within your _venv_ navigate to the folder `lib/python3.5/site-packages/homeassistant/components/homematic`. There you'll find the file `__init__.py`. At line 65 it should look like [this](https://github.com/home-assistant/home-assistant/blob/688bdc6532e514afbdc8efd1f574a7b5c9e8d280/homeassistant/components/homematic/__init__.py#L65) right now. Those lists are mapping of HomeMatic devices to Home Assistant components. Because the Hm-MIOB is a mixture, you'll have to add the pyhomematic class `IPMultiIO` (which you have added in the previous step) to the lists of: `DISCOVER_SWITCHES`, `DISCOVER_SENSORS` and `DISCOVER_BINARY_SENSORS`.

As soon as that is done you should be able to start Home Assistant again and get 2 switches and a lot of sensors. 2 of each `CHANGE_OVER`, `EXTERNAL_CLOCK` etc., and one `LEVEL`. The `LEVEL` will be the state of the channel you have mentioned you would like to control. Unfortunately I won't be able to add that as a nice UI element to control. But you should be able to control it in automations by using the [homematic.set_device_value](https://www.home-assistant.io/components/homematic/#services) service.

For the two switches you have to report if my implementation using the channels 2 and 6 was correct. If not, you may have spotted these numbers in the pyhomematic code. Replacing them by 3 and 7 should get them working if 2 and 6 did not work.

If you also have something attached to the inputs, it would be good to know what kind of events the CCU actually sends. I think all those sensors are actually not really useful. If I understand correctly what these sensors do, then they don't really set the sensor to `true` or `false`, but instead send events like buttons do (`PRESS_SHORT` etc.). So for example the external clock would be an event every second. To observe these events you can set the loglevel of HomeMatic related events to `debug` like this:

```yaml
logger:
  default: warning
  logs:
    homeassistant.components.homematic: debug
    pyhomematic: debug
```

It would also be useful to see the regular Status of this device. Especially for the sensors and the analogue output. Seeing how the interaction within the CCU looks like will help me to judge what it should be in Home Assistant.

**Comment by mobelix79** [comment]
Hi. Great step by step instructions, thanks. I will try to setup a test environment and provide the requested information as soon as possible. I can't promise but I hope and can do this during the upcoming week.

**Comment by mobelix79** [comment]
Hi. First feedback after setting up a test environment:
- general integration worked perfect, I can see all the new sensors
- for the switches we need 3 and 7 instead of 2 and 6. After changing to 3/7 the switches worked
- I was able to set the level using the mentioned set_device_value service, so works as well
- I have nothing attached to the inputs so I don't know if I can provide more additional information. But if so please let me know and I will try to help

So for me personally it looks already very good.

**Comment by danielperna84** [comment]
I have changed the channels. I guess for the sensors for now we leave it like that. As soon as someone with the same device comes along and reports that it's not working as it should be, we can improve the implementation.

**Comment by mobelix79** [comment]
Hi, sounds good. Thanks a lot for your support

**Pull request merged**
