### PR TITLE
0.1.67

### PR DESCRIPTION
**Pull request by danielperna84**
Version 0.1.67

This pull request:
- Some refactoring
- adds support for HomeMatic devices: HmIP-SWDO-P, HmIP-SMI55, HmIP-DSD-PCB, HmIPW-DRS4, HmIPW-DRS8, HmIPW-DRI32, HmIPW-DRI16, HmIP-DBB, HB-UNI-Sen-WEA
  - New classes: MotionIPV2, IPRemoteMotionV2, IPWSwitch, IPWInputDevice, HBUNISenWEA
- Improve support for HmIP-MOD-HO, HmIP-MOD-TM

What needs to be done in HA:
#### In binary_sensor.py add
```python
    "MotionIPV2": DEVICE_CLASS_MOTION,
    "IPRemoteMotionV2": DEVICE_CLASS_MOTION,
```

#### In const.py add
```python
# DISCOVER_SWITCHES
        "IPWSwitch",
# DISCOVER_SENSORS
        "IPRemoteMotionV2",
        "HBUNISenWEA",
...
# DISCOVER_BINARY_SENSORS
        "IPRemoteMotionV2",
        "IPWInputDevice",
```

### CODE REVIEW

**Comment by HRintc** [comment]
Hi!

Quick question here. I got a HmIP-DSD-PCB. It shows up in HomeAssistant but the state does not change. In HomeMatic it works fine.

Should it be set to button, switch or opening in HomeMatic?

I also tried if I get a keypress event in HomeAssistant. I did not. Any ideas?

**Comment by danielperna84** [comment]
@HRintc 

I didn't do the implementation and don't have the device to confirm. But by looking at the code I assume it should be a binary sensor that flips on / off depending on the state.

@Ahrak 

Could you help out here?

**Comment by ProfDrYoMan** [comment]
Sorry posted with the wrong account: Question again:

Hi!

Quick question here. I got a HmIP-DSD-PCB. It shows up in HomeAssistant but the state does not change. In HomeMatic it works fine.

Should it be set to button, switch or opening in HomeMatic?

I also tried if I get a keypress event in HomeAssistant. I did not. Any ideas?

@danielperna84 can you please remove the reference to the other account in your comment? Thx.

**Comment by ProfDrYoMan** [comment]
Solution found. It is a Button. Needs to be bound one time in HomeMatic to a program an executed once. Then it shows up as event in HomeAssistant.

**Pull request merged**
