### PR TITLE
0.1.47

### PR DESCRIPTION
**Pull request by danielperna84**
- Fix HmIP-BWTH (Issue #151)
- Added HmIP-KRCA

Anything else that should get into this version?

### CODE REVIEW

**Comment by klada** [comment]
@danielperna84 Maybe we can also get #157 into the next version, because #155 also requires changes to home-assistant. I'll prepare a PR in the hass repo as well.

**Comment by danielperna84** [comment]
I have uploaded the new version. I will create a separate PR for this though.

**Comment by klada** [comment]
@danielperna84 That's great, you can also apply the change I made in home-assistant/home-assistant#16082 to the PR where you want to bump the version.

**Comment by danielperna84** [comment]
I did included that already. Thanks for the reminder anyways. 🙂 
This is my PR now: https://github.com/home-assistant/home-assistant/pull/16083

**Pull request merged**
