### PR TITLE
LOWBAT to channel 0 in HelperLowBat

### PR DESCRIPTION
**Pull request by flexkra**
This pull request:
- fixes issue: #279, #249, #231, #186, #183, ....
- does the following: Changed the channel of LOWBAT to 0 in HelperLowBat

I noticed that all **my** devices which do have a LOWBAT-Attribute on a channel other than 0 do also broadcast the LOWBAT-Attribute on channel 0 (MAINTENANCE). My guess is that every HM-Device which has a LOWBAT-Attribute in the documentation behaves likes this. 

pro:
- alot more battery powered devices can be supported which only include lowbat on channel 0 (like most remotes)

con:
- there might be exceptions which do not include LOWBAT in channel 0

### CODE REVIEW

**Comment by flexkra** [comment]
If this gets accepted devices like HM-RC-4 can be mapped to RemoteBattery

**Comment by danielperna84** [comment]
You might be right with your observation. I just _fear_ that if we do that, new issues will arise where for some reason the battery is not reported on channel 0. And honestly, it's starting to annoy me to fix these LOWBAT-issues because it seems as if we're running in circles.
I don't know how others handle it, but my solution to monitor battery states seems much simpler with a lot less effort: I have one automation that notifies me if there are service messages on my CCU. And if there are, I will have a look at the CCU anyways. And there I'll see which device is running low. Yes, there's the additional step of looking at the CCU from time to time. But in my opinion the service messages should be monitored in any case, because there could also be other problems on the CCU. So why bother monitoring all these devices if you just can monitor the service messages?

**Comment by flexkra** [comment]
Absolutly. It's kinda sad that for the Homamatic devices channel 0 is not documented like it is for the HomematicIP devices. So there is no way to say it's like this for sure. 
The risk of potential "bricking" an implementation is there but it could also implement battery sensors for every battery powered homematic devices. Since it's your project thats your choice if you are willing to risk it. So far I could only confirm it for HM-Sec-RHS and HM-Sec-SCo but noticed the lowbat attribute on channel 0 for all my battery powered devices. 

Your usecase with monitoring the service message does not work for me as it would only result in me looking a few times a day at communication errors which are 99% of my service messages. And having the option to use binary_sensors for whatever automation you want is better that needing one i guess.

**Comment by danielperna84** [comment]
Ok, looking good so far. But I'll tag you when people start complaining about broken battery-attributes. :-P
Is this ready to be merged or are there remaining devices you're looking at?

**Comment by flexkra** [comment]
Haha okay :D 

I accidently experimented on this branch. I will open a new pull request so the commit history doesn't get spammend.

**Pull request closed without merging**
