### PR TITLE
Fix missing Parameters

### PR DESCRIPTION
**Pull request by macrojames**
This pull request:
- fixes issue: HmIP-BWTH <Fault -5: 'Unknown Parameter value for value key: OPERATING_VOLTAGE'>
- fixes issue: HmIP-BWTH <Fault -5: 'Unknown Parameter value for value key: LOW_BAT'>
- fixes issue: HmIP-BROLL/FROLL <Fault -5: 'Unknown Parameter value for value key: WORKING'>

Refactoring the classes during #266 would be good idea.

If I find some time, I'll try to design something. I struggled with inheritance multiple times now.

### CODE REVIEW

**Comment by danielperna84** [comment]
Does my `IPBlind` class work reliably for you? I don't have such devices, so I couldn't verify they are working correctly. The user that did give it a try had trouble with his devices. I just don't recall where the communication about this device took place. 😕

**Comment by macrojames** [comment]
Yes that worked. Not perfect regarding the known issue with the level being 0 or 100 if the hardware switch was used.
I tried to add the activity status to home assistant but I ran out of time until I found it.

The keypress events didn't work on my first try but I don't use the events and couldn't tell if that worked before.

**Comment by danielperna84** [comment]
> Not perfect regarding the known issue with the level being 0 or 100 if the hardware switch was used.

So this is a problem present with the currently available implementation already? I just want to make sure that we don't loose functionality.

**Comment by macrojames** [comment]
Yes, already present and we can see the values in the log. It looks like a bug in the ccu, I found a posting in a forum.

**Pull request merged**
