### PR TITLE
 New master classes and Helper usage

### PR DESCRIPTION
**Pull request by dagobert**
I did not change any class names.

Now all standard Homematic sensors have the attributes:

- HelperRssiDevice
- HelperRssiPeer
- HelperLowBat

All HomematicIP sensors have the attributes:

- HelperRssiDevice
- HelperLowBatIP
- HelperOperatingVoltageIP

I have changed the use of main classes and it inheritance. The new top
class `SensorHm`, `SensorHmIP` include all Helper classes that are common
to all devices of the specific model line. `SensorHm` is for standard
Homematic devices and `SensorHmIP` for the newer IP version.

Also, the use of existing Helper classes is now implemented for all
sensor classes. to prepare for the next step of adding more Helper
classes and changing the class names I have partly copied the content of
a sensor class to a class that was until now inheriting a sensor class
of similar capability. An example is the Shutter class.

### CODE REVIEW

**Comment by danielperna84** [comment]
You can't include `HelperLowBat` in `HMSensor`. Not all sensors are battery powered. This has to remain as a separate helper that only gets subclassed when the device really needs it.
And you also can't combine `HelperRssiDevice` and `HelperRssiPeer`. In practice only one of those has a useful value. Which one it is depends on the device. Besides that, both expose the `get_rssi` method. Home Assistant is using this to get the ONE value that fits the device. So this has to be inheritet from on a per device level as well.

**Comment by dagobert** [comment]
> You can't include `HelperLowBat` in `HMSensor`. Not all sensors are battery powered. This has to remain as a separate helper that only gets subclassed when the device really needs it.

This time I have checked the devices in the list and found them all use batteries and at least homegear is documenting them also exposing LOWBAT. I would rather create a Helper that pops LOWBAT same as you have for wired devices and RSSI. A device not having LOWBAT would "only" throw a warning which users would report like I did with SABOTAGE.

> And you also can't combine `HelperRssiDevice` and `HelperRssiPeer`. In practice only one of those has a useful value. Which one it is depends on the device. Besides that, both expose the `get_rssi` method. Home Assistant is using this to get the ONE value that fits the device. So this has to be inheritet from on a per device level as well.

I have to disagree. I have many actors that expose both and bost have different values. Most of the time one is much higher than the other. Both are in general useful. A sensor is communicating unidirectional therefore, yes, only one is carrying the actual RSSI. Standard HM devices expose both attributes with one showing -64k. This is not useful in practice but it also does not create any warning or error. As you stated in an earlier answer, the user has to decide what to do with it.
The problem here is more catching most with least effort. Since it is not even leading to a warning we can integrate it and do not have to worry about HM sensors that either expose one or the other - interestingly my HM sensors expose PEER with a dB value compared to HMIP sensors that expose the dB value in DEVICE.

> Besides that, both expose the `get_rssi` method. Home Assistant is using this to get the ONE value that fits the device.

I have deep knowledge about this but I have made only two changes in the __init__ component of HASS homematic and at least the WebUI is showing both rssi values correctly. I admit that I have not yet written my automations to query them but is that a problem?

I replaced 

`'RSSI_DEVICE': ['rssi', {}],`

by

```
'RSSI_PEER': ['rssi_peer', {}],
'RSSI_DEVICE': ['rssi_device', {}],
```

That was all.

**Comment by danielperna84** [comment]
> I replaced
> 
> `'RSSI_DEVICE': ['rssi', {}],`
> 
> by
> 
> ```
> 'RSSI_PEER': ['rssi_peer', {}],
> 'RSSI_DEVICE': ['rssi_device', {}],
> ```
> That was all.

True. Again I still had the old implementation in my head where the method was being used. The changes you mention would fix that. Although that would be a breaking change. A minor one though. That being said: out of my 37 RF devices only 4 of them have both values. But ok, we'll go with the included helpers.

Hhmm, the `WiredSensor` is wired. And all wired devices don't have batteries. But yes, popping it out then would be fine too I guess.

**Comment by dagobert** [comment]
> True. Again I still had the old implementation in my head where the method was being used. The changes you mention would fix that. Although that would be a breaking change. A minor one though. That being said: out of my 37 RF devices only 4 of them have both values. But ok, we'll go with the included helpers.

I think merging this proposed PR will be a good decision and I will help you to fix problems if you get lots of feedback because of this. 
I [proposed the change](https://github.com/home-assistant/home-assistant/pull/20902) in the component and they proposed to add the new and add a comment to the old `rssi` to be deprecated. I sent a PR about this to HASS.

> Hhmm, the `WiredSensor` is wired. And all wired devices don't have batteries. But yes, popping it out then would be fine too I guess.

I already have not inherited SeonsorHmIP in WiredSensor. So, it is already taken care of and there is no need to pop.

**Comment by dagobert** [comment]
If you are fine with my PR I will start to do the same with `actors.py`.

**Pull request merged**
