### PR TITLE
Add support for HmIPW-Devices (DRS4/8, DRI16/32)

### PR DESCRIPTION
**Pull request by henningweiler**
Please point your pull request at the __devel__ branch. Also provide some information about the changes.

This pull request:
- contributes to discussion in issue: \#219 
- adds support for HomeMatic device: \"HmIPW-DRS4", "HmIPW-DRS8", "HmIPW-DRI32", "HmIPW-DRI16"
- New classes: IPWSwitch, IPWInputDevice, HelperDeviceTemperature

### CODE REVIEW

**Comment by danielperna84** [comment]
Am I correct that the HmIPW-DRI32 and HmIPW-DRI16 aren't fully functional because of the issues with resolving the paramsets?

**Comment by henningweiler** [comment]
@danielperna84, thanks for reviewing the PR! 
Actually, since CCU3 Firmware >= 3.49.17 the paramsets _do_ resolve nicely. With a lot of HMIPW-Devices (>10), this takes a while during first start (about 10sec for my 8 devices) but then runs smoothly. There indeed was a deadlock situation on a callback in the ReGaHSS module for the RPC-Server. 
By the time 3.49.17 came out, I'd already implemented a fully-working solution to connect hassio to the CCU3 (or raspmatic in my case) via NodeRed and MQTT for all my components. The code should work, though and @p0l0 can give it a shot to extend for other components as well 👍

**Comment by danielperna84** [comment]
> Actually, since CCU3 Firmware >= 3.49.17 the paramsets _do_ resolve nicely. With a lot of HMIPW-Devices (>10), this takes a while during first start (about 10sec for my 8 devices) but then runs smoothly. There indeed was a deadlock situation on a callback in the ReGaHSS module for the RPC-Server.

So eq3 has fixed the issue? That's great news! 😃 

Then I'll strip out the debug-logging in merge. Thanks a lot. 👍

**Comment by henningweiler** [comment]
Thanks for the cleanup and the merge @danielperna84 !

**Pull request merged**
