### PR TITLE
Update misc.py

### PR DESCRIPTION
**Pull request by maedball**
Please point your pull request at the __devel__ branch. Also provide some information about the changes.

This pull request:
- adds support for HomeMatic device: HmIP-MOD-RC8

### CODE REVIEW

**Comment by tsenger** [comment]
Will this patch for "HmIP-MOD-RC8" published in the next release? I was also about to submit a patch until I saw that it already exists in the "devel" branch.

**Comment by danielperna84** [comment]
@tsenger 

Even if I would publish a new release today, it wouldn't be included in the next Home Assistant release. And I want to give #420 a chance to be included as well. Still waiting on a response there.

**Comment by tsenger** [comment]
All fine. I will wait for it to be integrated into Home Assistant at some point. Is there a release cycle to estimate when new pyhomematic releases will be published in HA?

**Comment by danielperna84** [comment]
> Is there a release cycle to estimate when new pyhomematic releases will be published in HA?

No. Contributions to pyhomematic happen whenever someone decides to work on it. And I only publish a new release once enough contributions have been made to justify a new release. Hence no regular release cycle.

**Pull request merged**
